import { Product, PucAccount, LedgerEntry, UserAccount, RoleItem } from '../types/store';

export const INITIAL_ROLES: RoleItem[] = [
  { id: 'role-admin', name: 'Admin', description: 'Acceso total y configuración del sistema', modules: ['pos', 'products', 'inventory', 'ledger', 'dian', 'puc', 'users'], isSystem: true },
  { id: 'role-cajero', name: 'Cajero', description: 'Acceso a facturación POS y consulta de existencias', modules: ['pos', 'products'], isSystem: true },
  { id: 'role-contador', name: 'Contador', description: 'Acceso a libros contables, PUC, productos e inventario y DIAN', modules: ['products', 'inventory', 'ledger', 'dian', 'puc'], isSystem: true },
];
export const MOCK_USERS: UserAccount[] = [
  { id: 'usr-admin', name: 'Administrador General', email: 'admin', password: 'admin', roleId: 'role-admin', role: 'Admin', isActive: true },
  { id: 'usr-admin-email', name: 'Administrador Aztec', email: 'admin@aztec.co', password: 'admin', roleId: 'role-admin', role: 'Admin', isActive: true },
  { id: 'usr-2', name: 'Andrés Mora', email: 'cajero@aztec.co', password: '123', roleId: 'role-cajero', role: 'Cajero', isActive: true },
  { id: 'usr-3', name: 'Valentina Ruiz', email: 'contador@aztec.co', password: '123', roleId: 'role-contador', role: 'Contador', isActive: true },
];
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'AB-001',
    name: 'Café Juan Valdez 500g',
    category: 'Abarrotes',
    price: 28500,
    cost: 21000,
    stock: 24,
    minStock: 8,
    ivaRate: 0.19,
    barcode: '77020101',
  },
  {
    id: 'prod-2',
    sku: 'AB-002',
    name: 'Arroz Diana Premium 1kg',
    category: 'Abarrotes',
    price: 4800,
    cost: 3600,
    stock: 65,
    minStock: 15,
    ivaRate: 0.00, // Exento
    barcode: '77020102',
  },
  {
    id: 'prod-3',
    sku: 'AB-003',
    name: 'Aceite Premier Girasol 1000ml',
    category: 'Abarrotes',
    price: 16500,
    cost: 12800,
    stock: 5, // Low stock alert
    minStock: 10,
    ivaRate: 0.19,
    barcode: '77020103',
  },
  {
    id: 'prod-4',
    sku: 'LC-001',
    name: 'Leche Alquería Entera 1.1L',
    category: 'Lácteos',
    price: 4900,
    cost: 3900,
    stock: 42,
    minStock: 12,
    ivaRate: 0.00, // Exenta canasta básica
    barcode: '77020104',
  },
  {
    id: 'prod-5',
    sku: 'AS-001',
    name: 'Jabón Rey Barra 300g',
    category: 'Aseo',
    price: 3200,
    cost: 2200,
    stock: 50,
    minStock: 10,
    ivaRate: 0.19,
    barcode: '77020105',
  },
  {
    id: 'prod-6',
    sku: 'BE-001',
    name: 'Agua Cristal con Gas 600ml',
    category: 'Bebidas',
    price: 2500,
    cost: 1500,
    stock: 3, // Low stock alert
    minStock: 12,
    ivaRate: 0.19,
    barcode: '77020106',
  },
  {
    id: 'prod-7',
    sku: 'AB-004',
    name: 'Harina PAN Blanca 1kg',
    category: 'Abarrotes',
    price: 4600,
    cost: 3400,
    stock: 30,
    minStock: 10,
    ivaRate: 0.00,
    barcode: '77020107',
  },
  {
    id: 'prod-8',
    sku: 'SN-001',
    name: 'Papas Margarita Pollo 110g',
    category: 'Snacks',
    price: 5200,
    cost: 3800,
    stock: 18,
    minStock: 6,
    ivaRate: 0.19,
    barcode: '77020108',
  }
];

export const PUC_CATALOG: PucAccount[] = [
  { code: '1', name: 'ACTIVO', type: 'Activo', level: 1 },
  { code: '11', name: 'Disponible', type: 'Activo', level: 2 },
  { code: '1105', name: 'Caja', type: 'Activo', level: 3 },
  { code: '110505', name: 'Caja General (Efectivo POS)', type: 'Activo', level: 4 },
  { code: '1110', name: 'Bancos', type: 'Activo', level: 3 },
  { code: '111005', name: 'Bancos Nacionales (Transferencias / Tarjetas)', type: 'Activo', level: 4 },
  { code: '1435', name: 'Mercancías No Fabricadas por la Empresa', type: 'Activo', level: 3 },
  { code: '143501', name: 'Inventario Tienda / Abarrotes', type: 'Activo', level: 4 },
  { code: '2', name: 'PASIVO', type: 'Pasivo', level: 1 },
  { code: '2365', name: 'Retención en la Fuente', type: 'Pasivo', level: 3 },
  { code: '236540', name: 'Retefuente Compras (2.5%)', type: 'Pasivo', level: 4 },
  { code: '2368', name: 'Impuesto de Industria y Comercio Retenido (ReteICA)', type: 'Pasivo', level: 3 },
  { code: '236801', name: 'ReteICA Compras (9.66 por mil)', type: 'Pasivo', level: 4 },
  { code: '2408', name: 'Impuesto sobre las Ventas por Pagar (IVA)', type: 'Pasivo', level: 3 },
  { code: '240801', name: 'IVA Generado en Ventas (19%)', type: 'Pasivo', level: 4 },
  { code: '240802', name: 'IVA Descontable en Compras (19%)', type: 'Pasivo', level: 4 },
  { code: '4', name: 'INGRESOS', type: 'Ingresos', level: 1 },
  { code: '4135', name: 'Comercio al por Mayor y al por Menor', type: 'Ingresos', level: 3 },
  { code: '413501', name: 'Ventas en Mostrador POS Tienda', type: 'Ingresos', level: 4 },
  { code: '6', name: 'COSTOS DE VENTAS', type: 'Costos', level: 1 },
  { code: '6135', name: 'Costo de Venta Comercio', type: 'Costos', level: 3 },
  { code: '613501', name: 'Costo de Mercancías Vendidas', type: 'Costos', level: 4 }
];

export const INITIAL_LEDGER_ENTRIES: LedgerEntry[] = [
  {
    id: 'ent-1',
    transactionId: 'TX-2026-001',
    date: '2026-08-16 09:15',
    pucCode: '110505',
    pucName: 'Caja General',
    description: 'Venta Factura POS-001 (Efectivo)',
    debit: 57000,
    credit: 0,
  },
  {
    id: 'ent-2',
    transactionId: 'TX-2026-001',
    date: '2026-08-16 09:15',
    pucCode: '413501',
    pucName: 'Comercio al por menor',
    description: 'Venta Factura POS-001 (Base)',
    debit: 0,
    credit: 47899,
  },
  {
    id: 'ent-3',
    transactionId: 'TX-2026-001',
    date: '2026-08-16 09:15',
    pucCode: '240801',
    pucName: 'IVA Generado (19%)',
    description: 'IVA Venta POS-001',
    debit: 0,
    credit: 9101,
  },
  {
    id: 'ent-4',
    transactionId: 'TX-2026-002',
    date: '2026-08-16 10:40',
    pucCode: '111005',
    pucName: 'Bancos Nacionales (Nequi)',
    description: 'Venta Factura POS-002 (Transferencia)',
    debit: 34100,
    credit: 0,
  },
  {
    id: 'ent-5',
    transactionId: 'TX-2026-002',
    date: '2026-08-16 10:40',
    pucCode: '413501',
    pucName: 'Comercio al por menor',
    description: 'Venta Factura POS-002 (Base)',
    debit: 0,
    credit: 34100,
  }
];
