import { PucAccount } from '../types/puc';

export const PUC_CATALOG: PucAccount[] = [
  { code: '1', name: 'ACTIVO', level: 'CLASE', nature: 'DEBITO', acceptsMovement: false },
  { code: '11', name: 'DISPONIBLE', level: 'GRUPO', nature: 'DEBITO', acceptsMovement: false, parentCode: '1' },
  { code: '1105', name: 'CAJA', level: 'CUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '11' },
  { code: '110505', name: 'Caja General', level: 'SUBCUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '1105' },
  { code: '11050501', name: 'Caja Principal Moneda Nacional', level: 'AUXILIAR', nature: 'DEBITO', acceptsMovement: true, parentCode: '110505' },
  { code: '1110', name: 'BANCOS', level: 'CUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '11' },
  { code: '111005', name: 'Bancos Nacionales', level: 'SUBCUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '1110' },
  { code: '11100501', name: 'Bancolombia Cta Corriente #1029', level: 'AUXILIAR', nature: 'DEBITO', acceptsMovement: true, parentCode: '111005' },
  { code: '1305', name: 'CLIENTES', level: 'CUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '13' },
  { code: '130505', name: 'Clientes Nacionales', level: 'SUBCUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '1305' },
  { code: '13050501', name: 'Cartera Clientes Comerciales', level: 'AUXILIAR', nature: 'DEBITO', acceptsMovement: true, parentCode: '130505' },
  { code: '1355', name: 'ANTICIPO DE IMPUESTOS Y SALDOS A FAVOR', level: 'CUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '13' },
  { code: '135515', name: 'Retención en la Fuente 2.5%', level: 'AUXILIAR', nature: 'DEBITO', acceptsMovement: true, parentCode: '1355' },
  { code: '135518', name: 'Impuesto de Industria y Comercio Retenido (ReteICA)', level: 'AUXILIAR', nature: 'DEBITO', acceptsMovement: true, parentCode: '1355' },
  { code: '2', name: 'PASIVO', level: 'CLASE', nature: 'CREDITO', acceptsMovement: false },
  { code: '2205', name: 'PROVEEDORES NACIONALES', level: 'CUENTA', nature: 'CREDITO', acceptsMovement: false, parentCode: '22' },
  { code: '220505', name: 'Proveedores Nacionales Directos', level: 'AUXILIAR', nature: 'CREDITO', acceptsMovement: true, parentCode: '2205' },
  { code: '2365', name: 'RETENCIÓN EN LA FUENTE', level: 'CUENTA', nature: 'CREDITO', acceptsMovement: false, parentCode: '23' },
  { code: '236540', name: 'Retención Compras 2.5%', level: 'AUXILIAR', nature: 'CREDITO', acceptsMovement: true, parentCode: '2365' },
  { code: '2368', name: 'IMPUESTO DE INDUSTRIA Y COMERCIO RETENIDO', level: 'CUENTA', nature: 'CREDITO', acceptsMovement: false, parentCode: '23' },
  { code: '236805', name: 'ReteICA Compras Comerciales', level: 'AUXILIAR', nature: 'CREDITO', acceptsMovement: true, parentCode: '2368' },
  { code: '2408', name: 'IMPUESTO SOBRE LAS VENTAS POR PAGAR', level: 'CUENTA', nature: 'CREDITO', acceptsMovement: false, parentCode: '24' },
  { code: '240801', name: 'IVA Generado 19%', level: 'AUXILIAR', nature: 'CREDITO', acceptsMovement: true, parentCode: '2408' },
  { code: '240802', name: 'IVA Descontable 19%', level: 'AUXILIAR', nature: 'DEBITO', acceptsMovement: true, parentCode: '2408' },
  { code: '3', name: 'PATRIMONIO', level: 'CLASE', nature: 'CREDITO', acceptsMovement: false },
  { code: '3115', name: 'APORTES SOCIALES', level: 'CUENTA', nature: 'CREDITO', acceptsMovement: false, parentCode: '31' },
  { code: '311505', name: 'Capital Autorizado y Pagado', level: 'AUXILIAR', nature: 'CREDITO', acceptsMovement: true, parentCode: '3115' },
  { code: '3605', name: 'UTILIDAD DEL EJERCICIO', level: 'CUENTA', nature: 'CREDITO', acceptsMovement: true, parentCode: '36' },
  { code: '4', name: 'INGRESOS', level: 'CLASE', nature: 'CREDITO', acceptsMovement: false },
  { code: '4135', name: 'COMERCIO AL POR MAYOR Y AL POR MENOR', level: 'CUENTA', nature: 'CREDITO', acceptsMovement: false, parentCode: '41' },
  { code: '413505', name: 'Venta de Productos Comerciales', level: 'AUXILIAR', nature: 'CREDITO', acceptsMovement: true, parentCode: '4135' },
  { code: '5', name: 'GASTOS', level: 'CLASE', nature: 'DEBITO', acceptsMovement: false },
  { code: '5105', name: 'GASTOS DE PERSONAL', level: 'CUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '51' },
  { code: '510506', name: 'Sueldos y Salarios', level: 'AUXILIAR', nature: 'DEBITO', acceptsMovement: true, parentCode: '5105' },
  { code: '5235', name: 'SERVICIOS', level: 'CUENTA', nature: 'DEBITO', acceptsMovement: false, parentCode: '52' },
  { code: '523560', name: 'Publicidad y Propaganda', level: 'AUXILIAR', nature: 'DEBITO', acceptsMovement: true, parentCode: '5235' },
  { code: '6', name: 'COSTOS DE VENTAS', level: 'CLASE', nature: 'DEBITO', acceptsMovement: false },
  { code: '6135', name: 'COMERCIO AL POR MAYOR Y AL POR MENOR', level: 'CUENTA', nature: 'DEBITO', acceptsMovement: true, parentCode: '61' },
];